version: '2'
services:
  nginx:
    image: 'prooph/nginx:www'
    volumes:
      - ./env/gateway:/etc/nginx/sites-enabled:ro
      - .:/var/www
      - ./frontend/dist:/var/www/public/dist
    ports:
      - '8111:80'
  php:
    image: prooph/php:7.1-fpm
    volumes:
      - .:/var/www
    environment:
     #@TODO: move to app.env file
     # Set PROOPH_ENV=prod for production
      - PROOPH_ENV=dev
      - PDO_DSN=pgsql:host=postgres port=5432 dbname=pes_mgmt_ui
      - PDO_USER=postgres
      - PDO_PWD=

  node:
    image: node:latest
    volumes:
      - ./frontend:/usr/local/app
    working_dir: /usr/local/app

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pes_mgmt_ui
    volumes:
      - ./env/postgres/initdb.d:/docker-entrypoint-initdb.d:ro